#!/usr/bin/env python3
"""Build the derived aoa-models decision lookup from canonical records."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
import re
import sys


ROOT = Path(__file__).resolve().parents[1]
DECISIONS = ROOT / "docs" / "decisions"
OUTPUT = ROOT / "generated" / "decision-index.md"
NAME_RE = re.compile(r"^(AOA-MODELS-D-(\d{4}))-[a-z0-9][a-z0-9-]*\.md$")


@dataclass(frozen=True)
class Record:
    decision_id: str
    number: int
    title: str
    date: str
    posture: str
    path: Path


def _field(lines: list[str], key: str) -> str:
    prefix = f"- {key}:"
    for line in lines:
        if line.startswith(prefix):
            return line.split(":", 1)[1].strip()
    return ""


def collect() -> tuple[list[Record], list[str]]:
    records: list[Record] = []
    issues: list[str] = []
    for path in sorted(DECISIONS.glob("AOA-MODELS-D-*.md")):
        match = NAME_RE.match(path.name)
        if not match:
            issues.append(f"{path.relative_to(ROOT)}: invalid canonical filename")
            continue
        lines = path.read_text(encoding="utf-8").splitlines()
        title = next((line[2:].strip() for line in lines if line.startswith("# ")), "")
        decision_id = _field(lines, "Decision ID")
        date = _field(lines, "Original date")
        posture = _field(lines, "Posture")
        if decision_id != match.group(1):
            issues.append(f"{path.relative_to(ROOT)}: Decision ID must match filename")
        if not title or not date or not posture:
            issues.append(f"{path.relative_to(ROOT)}: title, date, and posture are required")
        if decision_id and title and date and posture:
            records.append(
                Record(decision_id, int(match.group(2)), title, date, posture, path)
            )
    if not records:
        issues.append("docs/decisions: no canonical decision records")
    numbers = [record.number for record in records]
    if len(numbers) != len(set(numbers)):
        issues.append("docs/decisions: duplicate decision number")
    return records, issues


def render(records: list[Record]) -> str:
    lines = [
        "# Decision index",
        "",
        "> Generated by `scripts/generate_decision_index.py`; do not edit.",
        "",
    ]
    for record in sorted(records, key=lambda item: item.number):
        rel = record.path.relative_to(ROOT).as_posix()
        lines.append(
            f"- [{record.decision_id} - {record.title}](../{rel}) "
            f"- {record.date}; `{record.posture}`"
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    records, issues = collect()
    if issues:
        for issue in issues:
            print(f"ERROR: {issue}", file=sys.stderr)
        return 1
    expected = render(records)
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != expected:
            print(f"ERROR: {OUTPUT.relative_to(ROOT)} is missing or stale", file=sys.stderr)
            return 1
        print(f"OK: {len(records)} decision record(s); generated index is current")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)} from {len(records)} decision record(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
